[WIP] WireGuard
eduvpn/python-eduvpn-client pull request #466
Opened 2022-03-07 17:43 UTC by alvra

First draft of WireGuard support.

Currently allows connecting to supporting servers, but the UI doesn't register the connection.

2022-04-05 08:20 UTC, gijzelaerr requested changes
I can't get wireguard to work, see chat discussion in slack for details.

2 issues:
 * I can't connect to `vpn-next.tuxed.net` and I don't know why, I don't get an error.
 * If I then connect to a different VPN server a need to select a profile, the list here seems to be the `vpn-next.tuxed.net` list. If I select one I get the error:
 
```
Traceback (most recent call last):
  File "/home/gijs/Work/surfnet/python-eduvpn-client/eduvpn/interface/event.py", line 165, in on_chosen_profile
    connection = connect_server_info.connect(app, profile, oauth_session)
  File "/home/gijs/Work/surfnet/python-eduvpn-client/eduvpn/server.py", line 261, in connect
    remote.check_response(response)
  File "/home/gijs/Work/surfnet/python-eduvpn-client/eduvpn/remote.py", line 52, in check_response
    uri = response.history[0].url
IndexError: list index out of range
```

2022-04-13 10:13 UTC, alvra commented on eduvpn/utils.py
> +        adapter = HTTPAdapter(max_retries=Retry(total=retries))
Please use 4 space indentation

2022-04-13 10:15 UTC, jwijenbergh commented on eduvpn/utils.py
> +        adapter = HTTPAdapter(max_retries=Retry(total=retries))
whoops, thanks

2022-04-13 10:21 UTC, alvra commented on eduvpn/nm.py
> +        except ValueError:
I prefer to keep the try branch as short as possible, with an `else` branch for the rest.

2022-04-13 10:23 UTC, alvra commented
Great addition @jwijenbergh!

2022-04-13 12:05 UTC, merged